name: CD
on:
  push:
    branches:
      - master
jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'chore')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Create Build
      run: npm run build
    - name: Deploy Build
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.JINA_DEV_BOT }}
        BRANCH: gh-pages
        FOLDER: build
    - uses: technote-space/toc-generator@v2
      with:
        MAX_HEADER_LEVEL: 2
        FOLDING: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TOC_TITLE: ''
        TARGET_PATHS: 'README.md'
        COMMIT_MESSAGE: 'chore(docs): update TOC'