name: Sync version with Jina core / JinaD
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '0.0.0'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: update version
      run: |
        echo "Updating version to ${{ github.event.inputs.version }}!"
        npm version ${github.event.inputs.version}
    - name: tag and push
      run: |
        git tag ${github.event.inputs.version}
        git push --follow-tags
        git push --tags